### ISSUE TITLE
Do not panic on exceeding 4096 prints per frame

### ISSUE THREAD

**Issue by nicopap** [nicopap/bevy-debug-text-overlay#5]
Currently, because we use a [`mpsc::SyncSender`](https://doc.rust-lang.org/stable/std/sync/mpsc/struct.SyncSender.html), we have to set a given max buffer size, I chose 4096. We assume it is never exceeded, which will panic if user once request more than 4096 messages at once. It is probably worthwhile not panicking.

**Comment by Nekith** [comment]
What would be the desired behaviour? Logging through `bevy_log`?

I reckon that propagating the `Result` would make `screen_print!` more cumbersome to use.

**Comment by nicopap** [comment]
You are right, logging an `error!` is the only sensible alternative.
